// Generated by gencpp from file project/AudioPlayerResponse.msg
// DO NOT EDIT!


#ifndef PROJECT_MESSAGE_AUDIOPLAYERRESPONSE_H
#define PROJECT_MESSAGE_AUDIOPLAYERRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace project
{
template <class ContainerAllocator>
struct AudioPlayerResponse_
{
  typedef AudioPlayerResponse_<ContainerAllocator> Type;

  AudioPlayerResponse_()
    : ack()  {
    }
  AudioPlayerResponse_(const ContainerAllocator& _alloc)
    : ack(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _ack_type;
  _ack_type ack;





  typedef boost::shared_ptr< ::project::AudioPlayerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::project::AudioPlayerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct AudioPlayerResponse_

typedef ::project::AudioPlayerResponse_<std::allocator<void> > AudioPlayerResponse;

typedef boost::shared_ptr< ::project::AudioPlayerResponse > AudioPlayerResponsePtr;
typedef boost::shared_ptr< ::project::AudioPlayerResponse const> AudioPlayerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::project::AudioPlayerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::project::AudioPlayerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::project::AudioPlayerResponse_<ContainerAllocator1> & lhs, const ::project::AudioPlayerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.ack == rhs.ack;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::project::AudioPlayerResponse_<ContainerAllocator1> & lhs, const ::project::AudioPlayerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace project

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::project::AudioPlayerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::project::AudioPlayerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project::AudioPlayerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::project::AudioPlayerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project::AudioPlayerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::project::AudioPlayerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::project::AudioPlayerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b6a73f722475d64a28238118997ef482";
  }

  static const char* value(const ::project::AudioPlayerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb6a73f722475d64aULL;
  static const uint64_t static_value2 = 0x28238118997ef482ULL;
};

template<class ContainerAllocator>
struct DataType< ::project::AudioPlayerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "project/AudioPlayerResponse";
  }

  static const char* value(const ::project::AudioPlayerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::project::AudioPlayerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string ack\n"
;
  }

  static const char* value(const ::project::AudioPlayerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::project::AudioPlayerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ack);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudioPlayerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::project::AudioPlayerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::project::AudioPlayerResponse_<ContainerAllocator>& v)
  {
    s << indent << "ack: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.ack);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PROJECT_MESSAGE_AUDIOPLAYERRESPONSE_H
