// Generated by gencpp from file project/Text2Speech.msg
// DO NOT EDIT!


#ifndef PROJECT_MESSAGE_TEXT2SPEECH_H
#define PROJECT_MESSAGE_TEXT2SPEECH_H

#include <ros/service_traits.h>


#include <project/Text2SpeechRequest.h>
#include <project/Text2SpeechResponse.h>


namespace project
{

struct Text2Speech
{

typedef Text2SpeechRequest Request;
typedef Text2SpeechResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Text2Speech
} // namespace project


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::project::Text2Speech > {
  static const char* value()
  {
    return "8be93dfc13258654eb30fdcda5227e42";
  }

  static const char* value(const ::project::Text2Speech&) { return value(); }
};

template<>
struct DataType< ::project::Text2Speech > {
  static const char* value()
  {
    return "project/Text2Speech";
  }

  static const char* value(const ::project::Text2Speech&) { return value(); }
};


// service_traits::MD5Sum< ::project::Text2SpeechRequest> should match
// service_traits::MD5Sum< ::project::Text2Speech >
template<>
struct MD5Sum< ::project::Text2SpeechRequest>
{
  static const char* value()
  {
    return MD5Sum< ::project::Text2Speech >::value();
  }
  static const char* value(const ::project::Text2SpeechRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::project::Text2SpeechRequest> should match
// service_traits::DataType< ::project::Text2Speech >
template<>
struct DataType< ::project::Text2SpeechRequest>
{
  static const char* value()
  {
    return DataType< ::project::Text2Speech >::value();
  }
  static const char* value(const ::project::Text2SpeechRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::project::Text2SpeechResponse> should match
// service_traits::MD5Sum< ::project::Text2Speech >
template<>
struct MD5Sum< ::project::Text2SpeechResponse>
{
  static const char* value()
  {
    return MD5Sum< ::project::Text2Speech >::value();
  }
  static const char* value(const ::project::Text2SpeechResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::project::Text2SpeechResponse> should match
// service_traits::DataType< ::project::Text2Speech >
template<>
struct DataType< ::project::Text2SpeechResponse>
{
  static const char* value()
  {
    return DataType< ::project::Text2Speech >::value();
  }
  static const char* value(const ::project::Text2SpeechResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PROJECT_MESSAGE_TEXT2SPEECH_H
