// Generated by gencpp from file nao_nodes/AudioPlayerRequest.msg
// DO NOT EDIT!


#ifndef NAO_NODES_MESSAGE_AUDIOPLAYERREQUEST_H
#define NAO_NODES_MESSAGE_AUDIOPLAYERREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace nao_nodes
{
template <class ContainerAllocator>
struct AudioPlayerRequest_
{
  typedef AudioPlayerRequest_<ContainerAllocator> Type;

  AudioPlayerRequest_()
    : path()  {
    }
  AudioPlayerRequest_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> const> ConstPtr;

}; // struct AudioPlayerRequest_

typedef ::nao_nodes::AudioPlayerRequest_<std::allocator<void> > AudioPlayerRequest;

typedef boost::shared_ptr< ::nao_nodes::AudioPlayerRequest > AudioPlayerRequestPtr;
typedef boost::shared_ptr< ::nao_nodes::AudioPlayerRequest const> AudioPlayerRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::nao_nodes::AudioPlayerRequest_<ContainerAllocator1> & lhs, const ::nao_nodes::AudioPlayerRequest_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::nao_nodes::AudioPlayerRequest_<ContainerAllocator1> & lhs, const ::nao_nodes::AudioPlayerRequest_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace nao_nodes

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1d00cd540af97efeb6b1589112fab63e";
  }

  static const char* value(const ::nao_nodes::AudioPlayerRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1d00cd540af97efeULL;
  static const uint64_t static_value2 = 0xb6b1589112fab63eULL;
};

template<class ContainerAllocator>
struct DataType< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "nao_nodes/AudioPlayerRequest";
  }

  static const char* value(const ::nao_nodes::AudioPlayerRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string path\n"
;
  }

  static const char* value(const ::nao_nodes::AudioPlayerRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct AudioPlayerRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::nao_nodes::AudioPlayerRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::nao_nodes::AudioPlayerRequest_<ContainerAllocator>& v)
  {
    s << indent << "path: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.path);
  }
};

} // namespace message_operations
} // namespace ros

#endif // NAO_NODES_MESSAGE_AUDIOPLAYERREQUEST_H
