// Generated by gencpp from file nao_nodes/LoadUrl.msg
// DO NOT EDIT!


#ifndef NAO_NODES_MESSAGE_LOADURL_H
#define NAO_NODES_MESSAGE_LOADURL_H

#include <ros/service_traits.h>


#include <nao_nodes/LoadUrlRequest.h>
#include <nao_nodes/LoadUrlResponse.h>


namespace nao_nodes
{

struct LoadUrl
{

typedef LoadUrlRequest Request;
typedef LoadUrlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct LoadUrl
} // namespace nao_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_nodes::LoadUrl > {
  static const char* value()
  {
    return "5562f0f326dc984bc777bae8e1589603";
  }

  static const char* value(const ::nao_nodes::LoadUrl&) { return value(); }
};

template<>
struct DataType< ::nao_nodes::LoadUrl > {
  static const char* value()
  {
    return "nao_nodes/LoadUrl";
  }

  static const char* value(const ::nao_nodes::LoadUrl&) { return value(); }
};


// service_traits::MD5Sum< ::nao_nodes::LoadUrlRequest> should match
// service_traits::MD5Sum< ::nao_nodes::LoadUrl >
template<>
struct MD5Sum< ::nao_nodes::LoadUrlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_nodes::LoadUrl >::value();
  }
  static const char* value(const ::nao_nodes::LoadUrlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_nodes::LoadUrlRequest> should match
// service_traits::DataType< ::nao_nodes::LoadUrl >
template<>
struct DataType< ::nao_nodes::LoadUrlRequest>
{
  static const char* value()
  {
    return DataType< ::nao_nodes::LoadUrl >::value();
  }
  static const char* value(const ::nao_nodes::LoadUrlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_nodes::LoadUrlResponse> should match
// service_traits::MD5Sum< ::nao_nodes::LoadUrl >
template<>
struct MD5Sum< ::nao_nodes::LoadUrlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_nodes::LoadUrl >::value();
  }
  static const char* value(const ::nao_nodes::LoadUrlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_nodes::LoadUrlResponse> should match
// service_traits::DataType< ::nao_nodes::LoadUrl >
template<>
struct DataType< ::nao_nodes::LoadUrlResponse>
{
  static const char* value()
  {
    return DataType< ::nao_nodes::LoadUrl >::value();
  }
  static const char* value(const ::nao_nodes::LoadUrlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_NODES_MESSAGE_LOADURL_H
