// Generated by gencpp from file nao_nodes/Rest.msg
// DO NOT EDIT!


#ifndef NAO_NODES_MESSAGE_REST_H
#define NAO_NODES_MESSAGE_REST_H

#include <ros/service_traits.h>


#include <nao_nodes/RestRequest.h>
#include <nao_nodes/RestResponse.h>


namespace nao_nodes
{

struct Rest
{

typedef RestRequest Request;
typedef RestResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Rest
} // namespace nao_nodes


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::nao_nodes::Rest > {
  static const char* value()
  {
    return "b6a73f722475d64a28238118997ef482";
  }

  static const char* value(const ::nao_nodes::Rest&) { return value(); }
};

template<>
struct DataType< ::nao_nodes::Rest > {
  static const char* value()
  {
    return "nao_nodes/Rest";
  }

  static const char* value(const ::nao_nodes::Rest&) { return value(); }
};


// service_traits::MD5Sum< ::nao_nodes::RestRequest> should match
// service_traits::MD5Sum< ::nao_nodes::Rest >
template<>
struct MD5Sum< ::nao_nodes::RestRequest>
{
  static const char* value()
  {
    return MD5Sum< ::nao_nodes::Rest >::value();
  }
  static const char* value(const ::nao_nodes::RestRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_nodes::RestRequest> should match
// service_traits::DataType< ::nao_nodes::Rest >
template<>
struct DataType< ::nao_nodes::RestRequest>
{
  static const char* value()
  {
    return DataType< ::nao_nodes::Rest >::value();
  }
  static const char* value(const ::nao_nodes::RestRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::nao_nodes::RestResponse> should match
// service_traits::MD5Sum< ::nao_nodes::Rest >
template<>
struct MD5Sum< ::nao_nodes::RestResponse>
{
  static const char* value()
  {
    return MD5Sum< ::nao_nodes::Rest >::value();
  }
  static const char* value(const ::nao_nodes::RestResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::nao_nodes::RestResponse> should match
// service_traits::DataType< ::nao_nodes::Rest >
template<>
struct DataType< ::nao_nodes::RestResponse>
{
  static const char* value()
  {
    return DataType< ::nao_nodes::Rest >::value();
  }
  static const char* value(const ::nao_nodes::RestResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // NAO_NODES_MESSAGE_REST_H
