// Generated by gencpp from file sound_recognition/SoundRecognitionRequest.msg
// DO NOT EDIT!


#ifndef SOUND_RECOGNITION_MESSAGE_SOUNDRECOGNITIONREQUEST_H
#define SOUND_RECOGNITION_MESSAGE_SOUNDRECOGNITIONREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sound_recognition
{
template <class ContainerAllocator>
struct SoundRecognitionRequest_
{
  typedef SoundRecognitionRequest_<ContainerAllocator> Type;

  SoundRecognitionRequest_()
    {
    }
  SoundRecognitionRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> const> ConstPtr;

}; // struct SoundRecognitionRequest_

typedef ::sound_recognition::SoundRecognitionRequest_<std::allocator<void> > SoundRecognitionRequest;

typedef boost::shared_ptr< ::sound_recognition::SoundRecognitionRequest > SoundRecognitionRequestPtr;
typedef boost::shared_ptr< ::sound_recognition::SoundRecognitionRequest const> SoundRecognitionRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}


} // namespace sound_recognition

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sound_recognition/SoundRecognitionRequest";
  }

  static const char* value(const ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SoundRecognitionRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::sound_recognition::SoundRecognitionRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // SOUND_RECOGNITION_MESSAGE_SOUNDRECOGNITIONREQUEST_H
