// Generated by gencpp from file sound_recognition/SoundRecognitionResponse.msg
// DO NOT EDIT!


#ifndef SOUND_RECOGNITION_MESSAGE_SOUNDRECOGNITIONRESPONSE_H
#define SOUND_RECOGNITION_MESSAGE_SOUNDRECOGNITIONRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace sound_recognition
{
template <class ContainerAllocator>
struct SoundRecognitionResponse_
{
  typedef SoundRecognitionResponse_<ContainerAllocator> Type;

  SoundRecognitionResponse_()
    : label()  {
    }
  SoundRecognitionResponse_(const ContainerAllocator& _alloc)
    : label(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _label_type;
  _label_type label;





  typedef boost::shared_ptr< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SoundRecognitionResponse_

typedef ::sound_recognition::SoundRecognitionResponse_<std::allocator<void> > SoundRecognitionResponse;

typedef boost::shared_ptr< ::sound_recognition::SoundRecognitionResponse > SoundRecognitionResponsePtr;
typedef boost::shared_ptr< ::sound_recognition::SoundRecognitionResponse const> SoundRecognitionResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator1> & lhs, const ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator2> & rhs)
{
  return lhs.label == rhs.label;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator1> & lhs, const ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace sound_recognition

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ea23f97416b04c6151d2b576c0665ac1";
  }

  static const char* value(const ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xea23f97416b04c61ULL;
  static const uint64_t static_value2 = 0x51d2b576c0665ac1ULL;
};

template<class ContainerAllocator>
struct DataType< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "sound_recognition/SoundRecognitionResponse";
  }

  static const char* value(const ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string label\n"
;
  }

  static const char* value(const ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.label);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SoundRecognitionResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::sound_recognition::SoundRecognitionResponse_<ContainerAllocator>& v)
  {
    s << indent << "label: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.label);
  }
};

} // namespace message_operations
} // namespace ros

#endif // SOUND_RECOGNITION_MESSAGE_SOUNDRECOGNITIONRESPONSE_H
