(cl:defpackage project-srv
  (:use )
  (:export
   "AUDIOPLAYER"
   "<AUDIOPLAYER-REQUEST>"
   "AUDIOPLAYER-REQUEST"
   "<AUDIOPLAYER-RESPONSE>"
   "AUDIOPLAYER-RESPONSE"
   "TEXT2SPEECH"
   "<TEXT2SPEECH-REQUEST>"
   "TEXT2SPEECH-REQUEST"
   "<TEXT2SPEECH-RESPONSE>"
   "TEXT2SPEECH-RESPONSE"
  ))

